# Generated by Django 4.2.15 on 2024-10-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_companyinformation_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinformation',
            name='is_new',
        ),
    ]
